// Recursos legacy (existentes en v0.1.0).
export { ProductsResource } from './products.resource';
export { VariantsResource } from './variants.resource';
export { DocumentsResource } from './documents.resource';
export { ClientsResource } from './clients.resource';
export { PriceListsResource } from './price-lists.resource';
export { StocksResource } from './stocks.resource';
export { DocumentTypesResource } from './document-types.resource';
export { OfficesResource } from './offices.resource';
export { ShippingsResource } from './shippings.resource';
export { PaymentTypesResource } from './payment-types.resource';
export { StockReceptionsResource } from './stock-receptions.resource';
export { StockConsumptionsResource } from './stock-consumptions.resource';
export { ReturnsResource } from './returns.resource';
export { ThirdPartyDocumentsResource } from './third-party-documents.resource';
export { ProductTypesResource } from './product-types.resource';
export { UsersResource } from './users.resource';
export { ShippingTypesResource } from './shipping-types.resource';

// Recursos nuevos (v0.2.0).
export { PaymentsResource } from './payments.resource';
export { DynamicAttributesResource } from './dynamic-attributes.resource';
export { DiscountsResource } from './discounts.resource';
export { CurrenciesResource } from './currencies.resource';
export { SaleConditionsResource } from './sale-conditions.resource';
export { InstancesResource } from './instances.resource';
export { BookTypesResource } from './book-types.resource';
export { DteCodesResource } from './dte-codes.resource';
export { TaxesResource } from './taxes.resource';
export { StockConsumptionTypesResource } from './stock-consumption-types.resource';
export { CartsResource } from './carts.resource';
export { CheckoutsResource } from './checkouts.resource';
export { WebDescriptionsResource } from './web-descriptions.resource';
export { CollectionsResource } from './collections.resource';
export { VariantShippingResource } from './variant-shipping.resource';
export { CouponsResource } from './coupons.resource';
export { CourierOrdersResource } from './courier-orders.resource';
export { PaymentsGatewayResource } from './payments-gateway.resource';
